tsconfig/bases

bases/deno.json
scripts/create-npm-packages.ts
scripts/update-markdown-readme.ts
scripts/vendor/node-jsonc-parser/LICENSE.md
scripts/vendor/node-jsonc-parser/README.md
scripts/vendor/node-jsonc-parser/edit.ts
scripts/vendor/node-jsonc-parser/format.ts
scripts/vendor/node-jsonc-parser/jsonc.ts
scripts/vendor/node-jsonc-parser/parser.ts
scripts/vendor/node-jsonc-parser/scanner.ts

TypeScript allows comments in tsconfigs, and now so do we.

Adds a JSONC parser and support comments in tsconfigs

---

bases/svelte.json

To pair up with the TS Template

Adds a svelte TSConfig base

---

bases/svelte.json

re: https://github.com/sveltejs/svelte-preprocess/issues/206

Update svelte.json to set importsNotUsedAsValues

---

bases/svelte.json

This gets applies at preprocessor level anyway

Update svelte.json to use isolated modules

---

bases/svelte.json

As discussed in https://github.com/sveltejs/language-tools/issues/333

add sourceMap: true to Svelte tsconfig

---

.github/workflows/CI.yml
.github/workflows/deploy.yml
README.md
bases/node12.json
bases/recommended.json
bases/svelte.json
scripts/generate-recommend.ts
scripts/update-markdown-readme.ts

Done, it generates the recommended json by extracting it form the latest TS version

Start of generating a recommended from the tsconfig init

---

bases/deno.json
scripts/create-npm-packages.ts
template/README.md

Include the tsconfig JSON in the README on npm

---

bases/docusaurus.json

Adds the node + module aliases

Adds the types attribute'

---

README.md

Change "your in " to "in your"" in the Readme file

Made changes in the Readme file

---

README.md
bases/node14.json

Add node 14 config

---

bases/create-react-app.json

it also removed "include": ["src"] in create-react-app - it's not working as expected.

fix: remove "src" in create-react-app/tsconfig.json

---

scripts/create-npm-packages.ts

Closes #42
This does not remove the `"_version": "..."` line from the tsconfig, not sure if that is needed in your opinion. If it is I could add it.

Add _version to bump to specific versions

---

bases/nuxt.json

Source: https://typescript.nuxtjs.org/guide/setup

Add nuxt config

---

README.md
bases/node16.json

feat: add nodejs v16 base file

---

bases/svelte.json

Bumping didn't work as expected, revert change for 1.x
See #52 for more info

Svelte: Revert types removal

---

bases/node10.json

p.s. sorry for 3 PRs (it was faster for me to create changes with the github's edit feature)

remove extra spaces from node10 tsconfig

---

bases/next.json

Add base config for Next.js, source is the default tsconfig.json generated by Next CLI.

Add base config for Next.js

---

README.md
bases/cypress.json

Source is the recommended config in https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json

Add base config for Cypress

---

README.md
bases/remix.json

Source: https://github.com/remix-run/remix/blob/main/packages/create-remix/templates/_shared_ts/tsconfig.json

Remix TS Config 

---

bases/node10.json
bases/node12.json
bases/node14.json
bases/node16-strictest-esm.combined.json
bases/node16-strictest.combined.json
bases/node16.json
bases/node17.json
bases/node18.json

This pr sets `"moduleResolution": "node"` for all node-related configs

feat: set moduleResolution to node

---

bases/react-native.json

Exclude Node.js typings

---

README.md
bases/next-strictest.json

Added `tsconfig.json` for Next.js (strictest.

feat: Add next.js + strictest

---

bases/node-lts.json
bases/node16.json
bases/node17.json
bases/node18.json
bases/node19.json
bases/node20.json

Use `module: node16` for Node.js 16+

---

bases/strictest.json

Enable `isolatedModules` on `bases/strictest.json`

---

bases/bun.json

Update @tsconfig/bun to match bun defaults, see
https://github.com/oven-sh/bun/blob/2285735abd18b6d0a89a86feb57b21d2b0bda3a5/src/cli/tsconfig-for-init.json#L4

Update @tsconfig/bun to match bun defaults

---

README.md

It took me way too long to realise there actually is a node23 preset because it's missing from the table.

Add Node23 to README table

---

README.md
bases/node24.json

Node 24 already released several days ago: https://github.com/nodejs/node/releases/tag/v24.0.0

Support Node 24

---

bases/node22.json
bases/node23.json

Added libs implemented in node22.0.0 and node23.0.0

Add libs to node22.json and node23.json

---

bases/node24.json

https://github.com/tsconfig/bases/pull/299 Added these libraries to node 22 and 23. They also apply to node 24.

fix(node24): update lib to match node 24 runtime

---

.github/workflows/deploy.yml

Add support for provenance signing

---

.github/workflows/CI.yml
.gitignore
scripts/create-npm-packages.ts
template/README-combined.md
test/index.ts
test/package.json
test/pnpm-lock.yaml
test/tsconfig.json

Closes https://github.com/tsconfig/bases/issues/169, https://github.com/tsconfig/bases/issues/135
```sh
❯ tree packages/bases/
packages/bases/
├── bun.tsconfig.json
├── create-react-app.tsconfig.json
├── cypress.tsconfig.json
├── deno.tsconfig.json
├── docusaurus.tsconfig.json
├── ember.tsconfig.json
├── LICENSE
├── next.tsconfig.json
├── node10.tsconfig.json
├── node12.tsconfig.json
├── node14.tsconfig.json
├── node16.tsconfig.json
├── node17.tsconfig.json
├── node18.tsconfig.json
├── node19.tsconfig.json
├── node20.tsconfig.json
├── node21.tsconfig.json
├── node22.tsconfig.json
├── node23.tsconfig.json
├── node24.tsconfig.json
├── node-lts.tsconfig.json
├── node-ts.tsconfig.json
├── nuxt.tsconfig.json
├── package.json
├── qjsengine.tsconfig.json
├── react-native.tsconfig.json
├── …
```

feat: add @tsconfig/bases

---

scripts/deploy-changed-npm-packages.ts

Fixes https://github.com/tsconfig/bases/issues/327

ci: fix @tsconfig/bases deployment
