README.md
bases/react-native.json

This takes the template from the ts [react-native-template](https://github.com/react-native-community/react-native-template-typescript/blob/master/template/tsconfig.json), given that it's entirely generic right now I think this _could_ work for any RN app using `rn init`
Interesting that Expo's is a bit more bare: https://github.com/expo/expo/blob/master/templates/expo-template-bare-typescript/tsconfig.json
Fixes #8

Adds a React Native base template

---

bases/react-native.json

This updates the React Native config to support Array.includes and Object.{entries,values}, as specified by the [React Native JavaScript Environment documentation](https://reactnative.dev/docs/javascript-environment).

Add react native support for Array.includes and Object.{entries,values}

---

bases/node12.json

es2020.promise is only supported starting node>= 12.10.x, since the LTS listed on the website, is 12.18.x, I also enabled it.
See https://node.green/#ES2020

adjust node 12 config according to node.green

---

README.md
template/package.json

When accessing the npm website, there is no link to the Github repository, which makes it harder for users to find out which flags are being applied when they extend a base.

feat: Add repository on package.json template

---

bases/svelte.json

Was necessary to get completions for things such as `onMount`. Obsolete now because of this PR https://github.com/sveltejs/language-tools/pull/441 which adds the typings through `///` at the top of every svelte2tsx file.

Remove "types" from svelte base

---

bases/svelte.json

I was too quick on removing these from the types. They are needed for TypeScript files. If omitted, it will throw `Cannot find module './App.svelte' or its corresponding type declarations` errors.

Svelte: revert types removal

---

bases/create-react-app.json

Following #38, here is a base extracted from a brand new `create-react-app` as of today.
```
npx create-react-app --template typescript my-app
```
Tried to run deno following contributing docs but encountered an error
```bash
Developer/typescript/bases  patch ✗                                                                                                                                                                                                                                                                                                                                                                                             1m ⚑ ◒  ⍉
▶ deno run --allow-read --allow-run --allow-env --allow-write --allow-net scripts/generate-recommend.ts
npx: installed 1 in 1.265s
message TS6071: …
```

feat(bases): add create-react-app base

---

bases/node16.json

Discussed in #50. Without this TypeScript complains as `es2021` target is currently only available in 4.3 beta.

es2021 -> es2020

---

bases/svelte.json

Remove the `types` property from the Svelte base config. Having it in there was causing some confusion for people who needed access to other global types, because they were "removed" by having this `types` definition.
To not get TS errors for the now missing global Svelte definitions, users should add `/// <reference types="svelte" />` to a `d.ts` file instead, which will also load these global definitions.
Since this is a breaking change, the version is bumped to `2.0.0`

Svelte: Removes "types" property

---

scripts/create-npm-packages.ts

Logic of isBumpedVersionHigher was switched up. 
See #52 for more info
This needs to be merged _after_ #53

Fix bumping logic

---

bases/docusaurus.json

By default, 99,9% of users are going to use the Docusaurus classic theme anyway so it does not make sense to not include the classic theme types by default in the TS config, even if it creates some additional coupling, + it's possible to override it anyway.
When we'll have multiple themes in the future we'll create a shared package for common theme types (the Tailwind theme would have the same types as the classic theme). Still, we'll keep this coupling and bias toward the "official themes" by default for simplicity.
Related to https://github.com/facebook/docusaurus/issues/5282

Add @docusaurus/theme-classic to compilerOptions.types

---

bases/svelte.json

Since this requires TS 4.5 or higher, this requires a major version bump (please correct me if I'm wrong, but I think that's the case because TS will error on unknown flags). This can also be seen as a major change in behavior that some people may not want (yet), so that justifies the major version bump as well.

Use new preserveValueImports in Svelte config

---

scripts/create-npm-packages.ts

The `readme-extra` is not being applied on the npm currently. It corrects `readme-extra` search path, so it will be fixed.

fix: correct the readme-extra search path.

---

README.md
bases/strictest.json

Closes #68 
---
Not sure if `noPropertyAccessFromIndexSignature`, `noEmitOnError`, or `checkJs` should be included as they probably cause more problems than they solve.

Add @tsconfig/strictest

---

README.md
bases/node17.json

Self-explanatory; see #81.
I'm not sure about `useDefineForClassFields`, as it's enabled by default for `es2022` targets anyway.
Note: [lib][2] and [target][3] for 4.6 do support it - though it's RC, so it's understandable that the schema [hasn't been updated][1] yet.
[1]: https://json.schemastore.org/tsconfig
[2]: https://github.com/microsoft/TypeScript/blob/v4.6-rc/src/compiler/commandLineParser.ts#L36
[3]: https://github.com/microsoft/TypeScript/blob/v4.6-rc/src/compiler/commandLineParser.ts#L329

Add a base for Node 17

---

bases/node16-strictest-esm.combined.json
bases/node16-strictest.combined.json
bases/strictest.json

`alwaysStrict` will be turned on when `strict` is on, so no need to set it again
- per the TypeScript Website, related to some PRs I once made to it https://github.com/microsoft/TypeScript-Website/pull/500, https://github.com/microsoft/TypeScript-Website/pull/971
- only changed `strictest.json` and the two other configs generated from/combined with it
- afaik the rest of the settings are indeed additional and not set by `strict`

clean: remove extraneous alwaysStrict setting

---

README.md
bases/node18.json

According to https://node.green/#ES2022, Node 18 is 97% complete on ES2022 so should be safe to define it in both `target` and `lib`

Add base for node 18

---

README.md
bases/ember.json

- This is the base config used by Ember apps and addons. When actually consuemd via Ember CLI (e.g. ember-cli-typescript's blueprint), users will also get `compilerOptions.baseUrl`, `compilerOptions.paths`, and `include`, but extracting this allows us to use it as the shared guidance for Ember and Glimmer apps and addons which are *not* using `ember-cli-typescript` -- a situation which is currently unusual but will likely be the default by a year from now.
- We will also keep this up to date with the current recommendations of the [Semantic Versioning for TypeScript Types spec][spec] as it evolves over time.
[spec]: https://www.semver-ts.org

Add a base for Ember.js and related projects.

---

bases/ember.json

Eventually this will live in Ember's own docs, but not yet!

Ember: point to docs.ember-cli-typescript.com

---

bases/docusaurus.json

[Our E2E tests](https://github.com/facebook/docusaurus/runs/6811305014?check_suite_focus=true) are failing, because `moduleResolution: node` would not resolve the `exports` map. Instead of forcing `moduleResolution: NodeNext` on the users, who may not be on 4.7, I just added `skipLibCheck`.

Add skipLibCheck in docusaurus.json

---

bases/react-native.json

It makes sense and comes with `tsc --init` v4.7.4
Also noted in bases
- recommended
- create-react-app
- vite-react
- node16
- node10
- node 18
- node 17
- node 12
- next

Force consistent casing in file names in React Native base

---

.gitattributes

Per [the Linguist docs][docs], add an override for the bases so they get parsed and highlighted as JSON with Comments, rather than JSON, in line with the way Linguist [is configured for `tsconfig.json][config], so they don't look utterly terrible.
[docs]: https://github.com/github/linguist/blob/master/docs/overrides.md
[config]: https://github.com/github/linguist/blob/1fbaa41dc259695226bb4ffd70f43957df1b7fb6/lib/linguist/languages.yml#L3038
<details><summary>before this changes</summary>
</details>
<details><summary>with changes</summary>
</details>

Introduce .gitattributes for better syntax highlighting

---

bases/remix.json

Recently the Remix team added the following attrs to their default `tsconfig.json`:
```
"allowJs": true,
"forceConsistentCasingInFileNames": true,
```
I added them to this project's Remix base config as well.

Update Remix TS Config

---

bases/next.json

This PR updates the TSConfig to match the default TSConfig generated by Next.js v13 (with `app` folder enabled): https://github.com/vercel/next.js/blob/e0b04f22e39eb7138c195fcaa4a35bc004bdaefb/packages/create-next-app/templates/experimental-app/tsconfig.json

Update Next.js base to v13

---

scripts/deploy-changed-npm-packages.ts
scripts/generate-recommend.ts

It looks like Deno's stdlib was restructured here: https://github.com/denoland/deno_std/pull/813.
Some files/modules were marked deprecated and re-exported parts of the new modules. In this case, `std/io/bufio.ts` was deprecated in favor of `std/io/buffer.ts`. As of `std@0.159.0`, `std/io/bufio.ts` was removed completely.
To prevent similar issues in the future, it would be best to pin to a specific version using one of the following:
- Versioned import i.e. `import * as bufio from "https://deno.land/std@1.58.0/io/bufio.ts"
- Importmap
- Lock file
- Vendoring i.e. `deno vendor`

Fix deploy script

---

README.md
bases/node-lts-strictest-esm.combined.json
bases/node-lts-strictest.combined.json
bases/node-lts.json
scripts/generate-lts.ts

Due to package naming rules the nodeLts tsconfigs had to be renamed to node-lts. Please see the deploy failure [here](https://github.com/tsconfig/bases/actions/runs/3391252844/jobs/5636248749#step:6:32).

rename the nodeLts files to node-lts

---

bases/ember.json

Enable both `esModuleInterop` and `allowSyntheticDefaultImports`, since this matches the actual runtime behavior of Node 14+ with its ESM-CJS interop, as well as the behavior of all modern bundlers. Additionally, it aligns Ember with the upcoming `compilerOptions.module: "mixed"` mode, which adds explicit support for this pattern.

Ember: change ESM interop settings

---

bases/react-native.json

`skipLibCheck` makes it so that `tsc` will not typecheck library declarations. It was set in the previous TypeScript template, overriding the base @tsconfig/react-native, to avoid cases of duplicate identifiers between global types in React Native vs Node. I didn't enable it initially in the RN copy of the template since it reduces safety, didn't seem to cause issues in an example app, and wasn't the right place for the change compared to the base config.
In a more full repo I ran into the same issue. I was a bit confused, since specifying explicit `types` in `compilerOptions` would mean we are not brining it in for our own code. Telling tsc to ignore the Node types also isn't viable. Enabling `explainFiles`, I was able to see why it was being pulled in despite not being told to. In my …

Enable `skipLibCheck` for React Native tsconfig

---

bases/ember.json

As the Ember ecosystem is slowly migrating from DefinitelyTyped to natively-bundled types, libraries that tests against "floating dependencies" (i.e. no lockfile) in CI are running into a fun situation where they get the latest version of e.g.`@ember/test-helpers` that has its own types, but the presence of the empty `@types/ember__test-helpers` package in their dependencies causes errors like:
```
error TS2688: Cannot find type definition file for 'ember__test-helpers'.
The file is in the program because:
Entry point for implicit type library 'ember__test-helpers'
```
In the scenario above, explicitly setting `types: []` prevents `@types/ember__test-helpers` from being loaded _iff_ `@ember/test-helpers` is shipping its own types.
This also prevents globals from packages like …

Ember: default to `types: []`

---

bases/next.json

This PR updates the TSConfig to match the default TSConfig generated by Create Next App with the beta app folder enabled (`npx create-next-app --experimental-app`): https://github.com/vercel/next.js/blob/f0c7e72c7762740166a08e55af2e1d5b4961407b/packages/create-next-app/templates/app/ts/tsconfig.json

Update Next base to match latest Next.js template

---

bases/docusaurus.json

@slorber @Josh-Cena I've noticed that there are packages (e.g. [@docusaurus/plugin-content-docs](https://github.com/facebook/docusaurus/blob/7489f8729aad4ae4c09219eb2980f87a72554c72/packages/docusaurus-plugin-content-docs/package.json#L7-L21)) that are using the NPM `exports` property. However, TypeScript isn't configured in a way that allows access to these items.
Given that Node 16.14 is required since [2.0.0-beta.21](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.21), I suggest that we can now add `"moduleResolution": "Node16"`.
This allows the compiler and IDE to gather the proper information for usings the items in `exports`.

Support module resolution for package.json exports

---

bases/node18.json

According to node.green[^1] Node 18 supports ES2023 array features.
[^1]: https://node.green/#ES2023

Add `es2023` to Node 18

---

README.md
bases/node20.json

Node 20 is set to be released tomorrow[^1] (2023-04-18). The configuration should be identical to Node 18, as far as I can tell.
[^1]: https://github.com/nodejs/Release#release-schedule

Add Node 20

---

bases/react-native.json

The tsconfig already supports esnext syntax, but RN supports some newer libraries than the es2019 target.   This adds the libs where the types declared are implemented by Hermes as of current main branch (found via code search or internal searches) or an RN polypill (like for promise).
  I bumped the major here, so users on older versions of RN don’t get the new libs showing up as supported without explicitly updating. This will be accompanied by a change which bumps the version in our own template.

[react-native] Update list of suported libs

---

README.md
bases/node19.json

Closes #142 
After examination of https://node.green/ I found out that Node 19 capabilities are equal to Node 18.
Due to this issue: https://github.com/tsconfig/bases/issues/173 I'm making the version 1 first, having `"lib": ["es2022"]`, in order to support Typescript below version 5.
After that version 2 can be released similar to what Node 18 base looks like currently (having es2023 lib).

Node19 base

---

README.md

I think it is very useful with combined configurations to see the resulting outcome. Therefore, a reference to the necessary command for the TypeScript compiler should not be missing.

Add "tsc --showConfig" command to combine section in readme

---

bases/node19.json

with `es2023` lib (similar to Node 18 base v2).

Node 19 base v2

---

bases/nuxt.json

In the tsconfig generated by the create-nuxt-app repository, .nuxt and dist were also "excluded".
I thought this could be included in the common settings when using Nuxt.js.
https://github.com/nuxt/create-nuxt-app/blob/c4680b0018edefdd5de0a771858faa83c7d43b37/packages/cna-template/template/tsconfig.json

Update nuxt.json: Add .nuxt, dist to "exclude" to match create-nuxt-app.

---

bases/vite-react.json

In the [Announcing Typescript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler) blogpost, the Typescript team introduced the `moduleResolution: bundler` option.  
They say:
> If you are using a modern bundler like Vite, esbuild, swc, Webpack, Parcel, and others that implement a hybrid lookup strategy, the new bundler option should be a good fit for you.
This PR changes `moduleResolution` to the new strategy for the Vite React base.  
Please let me know if this change is also applicable to any other bases, then I will edit those as well.

Use `moduleResolution: bundler` for Vite React

---

bases/react-native.json

This lets TypeScript do ESM style resolution, including export maps, like:
```
exports: {
"foo": "src/foo.js",
"bar": "src/bar.js",
}
```
An out of the box typechecking in the RN TypeScript template will still resolve `node` instead of `react-native` or `default`, which isn't quite right, but this unblocks usage which isn't platform-specific, or cases where different platforms have the same types.
When RN starts targeting 5.0 we should consider changing it to `moduleResolution: "bundler"` and customizing the resolution behavior more in the RN template.
The version we ship this in (and whether we need to bump major again) depends on if we want to enable this for 0.72 vs 0.73.

[react-native] `moduleResolution: "nodenext"`

---

bases/react-native.json

We probably don't want this in 0.72 yet, since Metro won't work with this by default yet, and `moduleResolution: bundler` is better and slated to come to 0.73.

Move back to "moduleResolution: node"

---

bases/node20.json

#202 noted that the versioning was off, this migrates it inline with the rest of the bases

Update node20.json to match the same semver as the other nodes

---

bases/node-lts.json
bases/node16.json
bases/node17.json
bases/node18.json
bases/node20.json

This addresses the issue no. #209

fix:  inconsistent case for "module" field in node bases #209

---

README.md
bases/bun.json

Self explanatory, adds a base config for https://bun.sh borrowing the recommended config from [the documentation](https://bun.sh/docs/runtime/typescript#recommended-compileroptions)

add bun tsconfig base

---

bases/svelte.json

Strict mode is enabled in pretty much all other bases, and also SvelteKit. Seems like something that would make sense to enable here too
@dummdidumm

Enable strict mode for svelte.json

---

bases/ember.json

This is a breaking change for consumers of `@tsconfig/ember`, as they'll receive errors if they were not previously enforcing `import type` for type-imports.
Context:
- Already used in Ember's library blueprint: https://github.com/embroider-build/addon-blueprint/blob/main/files/__addonLocation__/tsconfig.json
- Already used in Svelte: https://github.com/tsconfig/bases/blob/main/bases/svelte.json#L14
The problem being solved here:
- https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/30
- Another repro: https://github.com/ember-template-imports/ember-template-imports/issues/207
- An option we have for solving these issues is to combine [`onlyRemoveTypeImports`](https://github.com/embroider-build/addon-blueprint/blob/main/files/__addonLocation__/babel.config.json#L3) and …

Ember: set verbatimModuleSyntax: true

---

README.md
bases/node21.json

Modeled after #171, this adds support for Node21.
Side-note, I checked [node.green](https://node.green), and found that Node.js 18.18.2, 19, and 20 all support ES2023. Should I update `"target"` of our corresponding presets to `es2023` to match that, now that the value is supported by the latest TypeScript version?
Closes #231
Closes #209 (already fixed by #210)

Support Node 21

---

README.md

As per linked issue, adds table at top with bases and their npm package names.
Closes #162

readme: Add table of contents

---

README.md
readme-extras/docusaurus.md
readme-extras/ember.md
readme-extras/nuxt.md
readme-extras/remix.md

This updates the documentation to add a notice that `baseUrl` may need to be set manually, for places where it is relevant.
But, checking the docs for [baseUrl](https://www.typescriptlang.org/tsconfig#baseUrl), it seems that it is only recommended for use with AMD module loaders (since TypeScript 4.1, it is no longer required when using 'paths`). So, I'm thinking it might be better just to remove the properties all together (with no documentation update)? That will still address the "confusion" from the linked issue, and not add "notices" that do not apply for most people.
Closes #223

Add `baseUrl` notices to readme

---

bases/bun.json

With bun `1.0.19`, types now lives in `@types/bun`, removing the need for `bun-types`.
Refs: https://bun.sh/blog/bun-v1.0.19#re-introducing-types-bun-formerly-bun-types

chore: remove `bun-types` (in favor of `@types/bun`)

---

bases/bun.json

This PR updates `@tsconfig/bun` to reflect changes on bun docs.
The changes are made recently to remove redundant options and fix inconsistency between docs and the generated `tsconfig.json` by the `bun init` command.
https://github.com/oven-sh/bun/pull/8654, https://github.com/oven-sh/bun/pull/8953
The tsconfig is based on https://bun.sh/docs/typescript#suggested-compileroptions.
I'm not sure we should include the stricter flags (`noUnusedLocals`, `noUnusedParameters`, `noPropertyAccessFromIndexSignature`) which are disabled by default in `bun init`, because we can enable them by the combination of `@tsconfig/bun` and `@tsconfig/strictest`.
ref: [`tsconfig-for-init.json`](https://github.com/oven-sh/bun/blob/main/src/cli/tsconfig-for-init.json)

Update @tsconfig/bun to reflect changes on bun docs

---

bases/ember.json

Reasons for doing this:
- we no longer use `ember-cli-typescript` and recommend _against_ its usage in new projects (the comment in the tsconfig.json here mentioned that the setting for `true` was to have ember-cli's error reporting screen pick up on type errors)
- `noEmitOnError` can break tools in silent ways, including `Glint`
- See:
- https://www.typescriptlang.org/tsconfig#noEmitOnError
> This defaults to false, making it easier to work with TypeScript in a watch-like environment where you may want to see results of changes to your code in another environment before making sure all errors are resolved. 
- https://github.com/typed-ember/glint/issues/599#issuecomment-1828191524
this is likely a bug in Glint, but people generally want to try out code rather than have the type-checker …

[Ember]: Set noEmitOnError to false

---

bases/create-react-app.json
bases/next.json
bases/node-lts.json
bases/node10.json
bases/node12.json
bases/node14.json
bases/node16.json
bases/node17.json
bases/node18.json
bases/node19.json
bases/node20.json
bases/node21.json
bases/react-native.json
bases/remix.json
bases/strictest.json
bases/svelte.json

Remove all `forceConsistentCasingInFileNames`. The default value is `true` since TypeScript 5.0 . And it will be deprecated later.
Only `@tsconfig/recommended` keep `forceConsistentCasingInFileNames` (although personally I think it should be removed).
Refer this issue and comment: https://github.com/microsoft/TypeScript/issues/51909#issuecomment-1385124052

Remove `forceConsistentCasingInFileNames`

---

bases/recommended.json

Set recommended target to `es2016`

---

bases/recommended.json
scripts/create-npm-packages.ts
scripts/generate-recommend.ts

resolve: https://github.com/tsconfig/bases/issues/180

Drop `display` field

---

bases/ember.json

The TypeScript docs for Ember have moved to the official guides. This PR updates the link in the base config.

chore: update docs link for Ember

---

bases/ember.json

[Ember]: set skipLibCheck: true

---

README.md
bases/node23.json

Node.js 23 was published on 2024-10-16 https://nodejs.org/en/blog/release/v23.0.0

Support Node 23

---

README.md
bases/qjsengine.json

This adds a config for targeting [QJSEngine](https://doc.qt.io/qt-5/qjsengine.html) an implementation of ES2016 (with some caveats) that Qt uses. In particular this is used by programs such as the [Mixxx](https://mixxx.org/) DJ software to allow plugin development with JavaScript.

Add QJSEngine config

---

README.md
bases/node-ts.json
readme-extras/node-ts.md
scripts/update-markdown-readme.ts

I'm adding the recommended file for node.js if you're running it with TypeScript type stripping through `--experimental-strip-types`
This is part of our [roadmap](https://github.com/nodejs/typescript/issues/24#issuecomment-2622195010).

Add recommended configuration for Node.js running TS natively

---

bases/node-ts.json

See [the added TS blog link](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#path-rewriting-for-relative-paths), but the TLDR is this is a version of `allowImportingTsExtensions` that works when building.
You need either one if you are importing TS files under node ts, but this does the actual transform to what node expects after build, so it's needed if you have code you want to both use in a script and when built. There doesn't seem to be a downside from reading the blog post?
Not sure about making `docs` an array, but it doesn't seem to be a member of the schema at least, so hopefully nobody is depending on the structure.

Add rewriteRelativeImportExtensions to node-ts

---

bases/ember.json

I'm not sure when declaration generation was added (maybe it was me :see_no_evil: haha), but in apps, its not correct to generate declarations.
declarations are meant for library dev.

[Ember] Disable declaration generation

---

bases/node20.json
bases/node21.json
bases/node22.json
bases/node23.json

Closes https://github.com/tsconfig/bases/issues/279
Set `module: nodenext` for node bases >= 20 (`node20`, `node21`, `node22`, `node23` bases) per typescript 5.8 recommendations
This adds support to `require(esm)` feature supported in node 22 and more recently node 20
- See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-8.html#support-for-require-of-ecmascript-modules-in---module-nodenext
- require(esm) in node20, https://nodejs.org/en/blog/release/v20.19.0/#requireesm-is-now-enabled-by-default
> TypeScript 5.8 supports this behavior under the --module nodenext flag. When --module nodenext is enabled, TypeScript will avoid issuing errors on these require() calls to ESM files.
> 
> Because this feature may be back-ported to older versions of Node.js, there is …

feat: set module: nodenext for node bases >=20

---

README.md

Fixes #287
The LTS thing including the Node version doesn't work long term; would be good to generate the table as a part of the script too.

Update table to include Node with TypeScript, fix LTS

---

README.md

Adds a missing `#` anchor in the link for the `node-ts` config
Fixes https://github.com/tsconfig/bases/pull/297#discussion_r2019742802
- the missing `#` meant that the link instead ended up incorrectly going to the non-existent file at `https://github.com/tsconfig/bases/blob/main/node-with-typescript-ts-58-only-tsconfigjson`, which would 404
The link now works; can view the [rendered commit](https://github.com/tsconfig/bases/blob/ff2dd6d5953ec4e5d977e187631d5b2f0bb86e31/README.md) to double check

docs: fix typo in `node-ts` anchor link

---

scripts/deploy-changed-npm-packages.ts

See https://docs.npmjs.com/generating-provenance-statements
> This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.

ci: npm publish generate provenance

---

bases/ember.json

New configs are here: https://github.com/ember-cli/tsconfigs
- For Apps: https://github.com/ember-cli/tsconfigs/tree/main/%40ember/app-tsconfig
- For Libraries: https://github.com/ember-cli/tsconfigs/tree/main/%40ember/library-tsconfig
:wave: 
When publishing this package next with the deprecation message, can you customize the message on NPM?
It should say something like:
```
@tsconfig/ember is deprecated. Please migrate to `@ember/app-tsconfig` or `@ember/library-tsconfig`
```
Thanks!

Deprecated @tsconfig/ember in favor of @ember/app-tsconfig and @ember/library-tsconfig

---

bases/node-ts.json

This aligns `node-ts.json` with the recommended tsconfig in the Node docs for built-in `*.ts` support.
https://nodejs.org/api/typescript.html#type-stripping
I realize this was discussed two months ago in https://github.com/tsconfig/bases/pull/293 but I missed that first time around and reading it back, it doesn't seem to directly answer the question of why these are not aligned.  So please consider this a low-urgency discussion topic rather than something to be landed.

node-ts: Align with Node docs (for discussion)

---

scripts/deploy-changed-npm-packages.ts

Currently the 'did anything change' check would not pass on the bases package from #320 - think this should be enough to handle that

Deploy bases when any other base changes
